name: Evaluate Model
on:
  workflow_run:
    workflows: ["Tests"]
    types: [completed]

jobs:
  evaluate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true  # Active le support Git LFS

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Git LFS
      run: |
        sudo apt-get update
        sudo apt-get install -y git-lfs
        git lfs install

    - name: Pull LFS files
      run: |
        git lfs pull

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install transformers torch

    - name: Verify model files
      run: |
        cd saved_models
        ls -lh
        file pytorch_model.bin  # Vérifie le type de fichier

    - name: Run evaluation
      run: |
        python -c "
        import json
        import torch
        from transformers import AutoModelForSequenceClassification, AutoTokenizer

        # Configuration
        model_dir = './saved_models'
        test_cases = [
            ('Super produit !', 1),
            ('Très déçu', 0),
            ('Je recommande', 1),
            ('Mauvaise qualité', 0),
            ('Excellent rapport qualité-prix', 1)
        ]

        # Chargement avec paramètres de sécurité
        tokenizer = AutoTokenizer.from_pretrained(model_dir)
        model = AutoModelForSequenceClassification.from_pretrained(
            model_dir,
            local_files_only=True,
            use_safetensors=False,
            torch_dtype=torch.float32
        )
        model.eval()

        # Évaluation
        correct = 0
        for text, expected in test_cases:
            inputs = tokenizer(text, return_tensors='pt', truncation=True, max_length=512)
            with torch.no_grad():
                outputs = model(**inputs)
            predicted = torch.argmax(outputs.logits).item()
            correct += (predicted == expected)

        accuracy = correct / len(test_cases)
        print(f'✅ Accuracy: {accuracy:.1%}')
        
        with open('metrics.json', 'w') as f:
            json.dump({
                'accuracy': accuracy,
                'tested_samples': len(test_cases),
                'model_format': 'pytorch'
            }, f)
        
        assert accuracy >= 0.85, f'❌ Accuracy {accuracy:.1%} < 85%'
        "

    - name: Upload metrics
      uses: actions/upload-artifact@v4
      with:
        name: model-metrics
        path: metrics.json